//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentEvolutionSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class assign_fac_sub_batch
    {
        public int fac_id { get; set; }
        public string sub { get; set; }
        public Nullable<int> m_id { get; set; }
        public string batch { get; set; }
    
        public virtual mentor_login mentor_login { get; set; }
    }
}
