//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentEvolutionSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class assign_task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assign_task()
        {
            this.task_checked_set = new HashSet<task_checked_set>();
        }
    
        public int task_id { get; set; }
        public int m_id { get; set; }
        public string title { get; set; }
        public string grade { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string sub { get; set; }
        public int isassign { get; set; }
    
        public virtual mentor_login mentor_login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task_checked_set> task_checked_set { get; set; }
    }
}
