//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentEvolutionSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class sem_sub
    {
        public int Id { get; set; }
        public int sem { get; set; }
        public string sub { get; set; }
        public string sub_code { get; set; }
        public int iselective { get; set; }
        public int isActive { get; set; }
    }
}
