//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentEvolutionSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student_login()
        {
            this.student_batch = new HashSet<student_batch>();
            this.task_cheched = new HashSet<task_cheched>();
        }
    
        public int id { get; set; }
        public Nullable<int> enro_id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public Nullable<int> contact { get; set; }
        public Nullable<int> m_id { get; set; }
    
        public virtual mentor_login mentor_login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student_batch> student_batch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task_cheched> task_cheched { get; set; }
    }
}
