//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentEvolutionSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_cheched
    {
        public int id { get; set; }
        public Nullable<int> enro_id { get; set; }
        public string batch { get; set; }
        public string title { get; set; }
        public string grade { get; set; }
        public string sub { get; set; }
        public Nullable<int> plagarisum { get; set; }
        public Nullable<int> sem { get; set; }
        public Nullable<int> f_id { get; set; }
    
        public virtual faculty_login faculty_login { get; set; }
        public virtual student_login student_login { get; set; }
    }
}
