//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentEvolutionSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_checked_set
    {
        public int id { get; set; }
        public Nullable<int> task_id { get; set; }
        public Nullable<int> p_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> @checked { get; set; }
        public string location { get; set; }
    
        public virtual assign_task assign_task { get; set; }
    }
}
